scss_files: 'src/**/*.scss'

linters:
  ColorVariable:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  IdSelector:
    enabled: false
  Indentation:
    character: space
    width: 2
  LeadingZero:
    enabled: false
  PropertySortOrder:
    enabled: false
  MergeableSelector:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  SpaceAroundOperator:
    enabled: false
